### ISSUE TITLE
Instagram eradication doesn't work

### ISSUE THREAD

**Issue by PrimozR** [jordwest/news-feed-eradicator#206] opened 2022-07-23 20:34 UTC
I recently enabled the newsfeed for Instagram (for 5 minutes), but I now still see the newsfeed even though I have it set in the extension to eradicate the newsfeed on IG. Twitter and Facebook don't cause problems.

Is there something going on with IG breaking compatibility or is the problem on my side?

**Comment by thejpanganiban** [comment] 2022-07-25 12:35
I have this issue as well!

**Comment by santidevhmo** [comment] 2022-07-25 15:32
I also have this issue on Firefox

**Comment by janjoost-denbrinker** [comment] 2022-07-26 13:31
duplicate of #203

**Comment by lyndonfroese** [comment] 2022-07-26 21:58
Same problem. It used to work but a few days ago it stopped. I'm guessing Instagram changed their code.

**Comment by jordwest** [comment] 2022-07-29 03:32
Fixed in v2.2.2, should be out in the next couple days after review

**Closed by jordwest** 2022-07-29 03:32 UTC
