### ISSUE TITLE
Not enough qoutes

### ISSUE THREAD

**Issue by jozefchmelar** [jordwest/news-feed-eradicator#15] opened 2016-02-25 18:51 UTC
:) I think you could add some more or make a script that would get them from quotes.reddit.com or heysaidso.com/

**Comment by troggy** [comment] 2016-04-03 19:54
Another quotes source is http://forismatic.com/en/ . They have API!

**Comment by jordwest** [comment] 2016-05-07 03:38
Duplicate of #6

**Closed by jordwest** 2016-05-07 03:38 UTC
Labels: in progress
