### ISSUE TITLE
Posts hidden in Facebook groups

### ISSUE THREAD

**Issue by pgclemens** [jordwest/news-feed-eradicator#85] opened 2020-04-26 13:16 UTC
Hello,
Recently discovered that content in Facebook groups is hidden thanks to NFE.
On the new version of fb, there are no signs at all of posts in groups and on the old version the most recent posts are blocked while the older ones further down are visible. Possible to fix? 💛 
![group in new fb](https://user-images.githubusercontent.com/64361397/80308717-b6520f80-87d0-11ea-8c89-b9d59de517d1.png)
![group in old fb](https://user-images.githubusercontent.com/64361397/80308719-b7833c80-87d0-11ea-9125-4fec3a985043.png)
Kind regards,
PC

**Comment by pgclemens** [comment] 2020-04-26 13:46
![extra](https://user-images.githubusercontent.com/64361397/80309339-b05e2d80-87d4-11ea-8c75-ea95ccd2733f.png)


A better example! Have tried removing cookies, and checked that everything is the most recent version.

**Comment by adjkant** [comment] 2020-04-26 17:08
+1 for this issue, seems to be caused by the most recent update.

**Comment by jordwest** [comment] 2020-04-27 00:23
Thanks for the report, confirmed on my end.

Thinking aloud:
Looks like the groups use the same `role="feed"` being used to hide the main news feed. The JS is disabled on routes other than the root, but the CSS can't be selectively applied. Thinking of perhaps adding a `data-nfe-disabled` attribute to the `html` tag to narrow the scope of the css selector.

**Comment by jordwest** [comment] 2020-04-27 01:51
Fixed in version `1.2.3`, currently in review with the add on stores

**Closed by jordwest** 2020-04-27 01:51 UTC

**Comment by pgclemens** [comment] 2020-04-27 06:31
@jordwest Fantastic! Thank you so much for making my and so many other peoples life easier every single day! 💛
