### ISSUE TITLE
News Feed Eradicator is not working on my Facebook 

### ISSUE THREAD

**Issue by reddcang** [jordwest/news-feed-eradicator#222] opened 2022-09-27 12:19 UTC
It suddenly doesn't work, but in the main page of the add-on, it says Facebook is 'eradicating' 

Let me know if there is any more info that i need to provide and how to solve this problem. Thank you

**Comment by mwm-cbus** [comment] 2022-09-27 13:04
Happened to me yesterday as well, with today starting to work again.
Maybe FB is testing some new layout code?

**Comment by jordwest** [comment] 2022-09-27 13:42
Please check that you're on v2.2.3, which was published earlier today.

Closing as duplicate of #218 for now.

**Closed by jordwest** 2022-09-27 13:42 UTC

**Comment by yothrowawaytoday** [comment] 2022-09-27 21:50
> Please check that you're on v2.2.3, which was published earlier today.
> 
> Closing as duplicate of #218 for now.

I'm on v2.2.3 on Chrome, but my Facebook news feed is still showing up. For a second, it's eradicated, but then the quote goes away and shows the feed.
