### ISSUE TITLE
Instagram feed not being blocked anymore.

### ISSUE THREAD

**Issue by kai-lovel** [jordwest/news-feed-eradicator#207] opened 2022-07-29 08:22 UTC
With Instagram enabled in settings, it appears the IG feed is still appearing.

**Comment by jordwest** [comment] 2022-07-29 11:37
Hi @kai-lovel, could you check which version you're running in your extension settings? This should be fixed in v2.2.2 but it only went out recently so your browser mightn't have updated yet

**Comment by jordwest** [comment] 2022-07-29 11:38
Will close this as duplicate of #205 for now

**Closed by jordwest** 2022-07-29 11:38 UTC

**Comment by kai-lovel** [comment] 2022-08-01 03:47
Thanks Jordan. Still on v2.2.1 but presume Chrome will push update shortly.

**Comment by kai-lovel** [comment] 2022-08-01 04:37
Working ✅
